### ISSUE TITLE
openaiapi调用代码在哪了呢

### ISSUE THREAD

**Issue by clclclaiggg** [KwaiKEG/CogGPT#2]
openai的api，请求网址没找到，在代码的哪里呢

**Comment by Lavonne-hub** [comment]
你好，openai的api调用代码在llms/clients.py文件中，需要在本地环境变量中设置api key

**Comment by clclclaiggg** [comment]
你好，我想改请求的网址可以嘛


---- 回复的原邮件 ----
| 发件人 | Yaojia ***@***.***> |
| 发送日期 | 2024年05月19日 23:05 |
| 收件人 | KwaiKEG/CogGPT ***@***.***> |
| 抄送人 | long ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [KwaiKEG/CogGPT] openaiapi调用代码在哪了呢 (Issue #2) |

你好，openai的api调用代码在llms/clients.py文件中，需要在本地环境变量中设置api key

**Comment by Lavonne-hub** [comment]
可以的，我们用的就是默认的openai网址，如果你想用自己的代理需要稍微改动一下代码，修改代理设置，具体可以参考openai的说明文档

---- 回复的原邮件 ----
| 发件人 | long ***@***.***> |
| 发送日期 | 2024年05月19日 23:13 |
| 收件人 | KwaiKEG/CogGPT ***@***.***> |
| 抄送人 | Yaojia ***@***.***>,
State ***@***.***> |
| 主题 | Re: [KwaiKEG/CogGPT] openaiapi调用代码在哪了呢 (Issue #2) |

你好，我想改请求的网址可以嘛


---- 回复的原邮件 ----
| 发件人 | Yaojia ***@***.***> |
| 发送日期 | 2024年05月19日 23:05 |
| 收件人 | KwaiKEG/CogGPT ***@***.***> |
| 抄送人 | long ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [KwaiKEG/CogGPT] openaiapi调用代码在哪了呢 (Issue #2) |

你好，openai的api调用代码在llms/clients.py文件中，需要在本地环境变量中设置api key
